<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Footdive" ignored="1" name="Default test(failed)" tests="2" failures="2" timestamp="15 Jul 2019 15:02:27 GMT" time="0.027" errors="0">
  <testcase name="test3" time="0.007" classname="Demo.TestNGRetryFailedDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Demo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.001" classname="Demo.TestNGRetryFailedDemo">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at Demo.TestNGRetryFailedDemo.test2(TestNGRetryFailedDemo.java:19)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.0" classname="Demo.TestNGRetryFailedDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
